# Value function of a deterministic policy

Evaluate the supplied 3×3 policy following `../Lesson03/Example_01_value_function.ipynb`. States are numbered left to right, top to bottom.

In [1]:
import numpy as np

**Policy**

<img src="Images/01_policy_deter_new.png" width="300">

In [2]:
# Parameters
gamma = 0.9

**Transition matrix** $P_\pi$

Rows represent current states and columns represent next states, both ordered $s_1,\ldots,s_9$.

$$P_\pi = \begin{bmatrix}
0&1&0&0&0&0&0&0&0\\
0&0&0&0&1&0&0&0&0\\
0&1&0&0&0&0&0&0&0\\
0&0&0&0&1&0&0&0&0\\
0&0&0&0&0&0&0&1&0\\
0&0&0&0&0&0&0&0&1\\
0&0&0&0&0&0&0&1&0\\
0&0&0&0&0&0&0&0&1\\
0&0&0&0&0&0&0&0&1
\end{bmatrix}$$

In [3]:
P_pi = np.array([
# s1 s2 s3 s4 s5 s6 s7 s8 s9
 [0, 1, 0, 0, 0, 0, 0, 0, 0],  # s1 -> s2
 [0, 0, 0, 0, 1, 0, 0, 0, 0],  # s2 -> s5
 [0, 1, 0, 0, 0, 0, 0, 0, 0],  # s3 -> s2
 [0, 0, 0, 0, 1, 0, 0, 0, 0],  # s4 -> s5
 [0, 0, 0, 0, 0, 0, 0, 1, 0],  # s5 -> s8
 [0, 0, 0, 0, 0, 0, 0, 0, 1],  # s6 -> s9
 [0, 0, 0, 0, 0, 0, 0, 1, 0],  # s7 -> s8
 [0, 0, 0, 0, 0, 0, 0, 0, 1],  # s8 -> s9
 [0, 0, 0, 0, 0, 0, 0, 0, 1],  # s9 -> s9
], dtype=float)

**Checking that the rows sum to 1 (stochastic matrix)**

$$\sum_{j=1}^{9} P_\pi[i,j] = 1.$$

In [4]:
print("Row sums:", np.sum(P_pi, axis=1))
np.testing.assert_allclose(P_pi.sum(axis=1), np.ones(9))

Row sums: [1. 1. 1. 1. 1. 1. 1. 1. 1.]


**Rewards vector**

$$r_\pi = [0,0,0,0,0,1,0,1,1]^T.$$

In [5]:
r_pi = np.array([0, 0, 0, 0, 0, 1, 0, 1, 1], dtype=float).reshape(-1, 1)
print("Rewards vector:\n", r_pi)

Rewards vector:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]]


**Identity matrix**

In [6]:
I = np.eye(9)

**Solving the Bellman equation** (with `np.linalg.solve`)

$$v_\pi = r_\pi + \gamma P_\pi v_\pi,$$
$$ (I-\gamma P_\pi)v_\pi = r_\pi.$$

In [7]:
M = I - gamma * P_pi
v = np.linalg.solve(M, r_pi)
print("Value function (direct):\n", np.array2string(v.reshape(3, 3), precision=2, floatmode="fixed"))

Value function (direct):
 [[ 7.29  8.10  7.29]
 [ 8.10  9.00 10.00]
 [ 9.00 10.00 10.00]]


**Solving the Bellman equation iteratively**

Starting from zeros, apply 100 updates:

$$v_{k+1} = r_\pi + \gamma P_\pi v_k.$$

In [8]:
v_old = np.zeros_like(r_pi)
for k in range(100):
    v_new = r_pi + gamma * (P_pi @ v_old)
    v_old = v_new
print("Value function (100 iterations):\n", np.array2string(v_new.reshape(3, 3), precision=2, floatmode="fixed"))

Value function (100 iterations):
 [[ 7.29  8.10  7.29]
 [ 8.10  9.00 10.00]
 [ 9.00 10.00 10.00]]
